# ---------------------------------------------------------------------------- #
#                                    BASICS                                    #
# ---------------------------------------------------------------------------- #
experiment_name: Eplus-TD3-training-example
environment: Eplus-5zone-hot-continuous-stochastic-v1
episodes: 5

# ---------------------------------------------------------------------------- #
#                                 SB3 ALGORITHM                                #
# ---------------------------------------------------------------------------- #
algorithm:
  name: stable_baselines3:TD3
  log_interval: 1
  parameters:
    policy: MlpPolicy
    learning_rate: 0.001
    buffer_size: 1000000
    learning_starts: 100
    batch_size: 100
    tau: 0.005
    gamma: 0.99
    train_freq:
      - 1
      - episode
    gradient_steps: -1
    action_noise: NormalActionNoise(mean=np.array([0]), sigma=np.array([0.1]))
    replay_buffer_class: null
    replay_buffer_kwargs: null
    optimize_memory_usage: false
    policy_delay: 2
    target_policy_noise: 0.2
    target_noise_clip: 0.5
    stats_window_size: 100
    tensorboard_log: null
    policy_kwargs: null
    verbose: 1
    seed: null
    device: auto
    _init_setup_model: true

# ---------------------------------------------------------------------------- #
#                             INITIAL STATE (MODEL)                            #
# ---------------------------------------------------------------------------- #

# -------------------------------- Local Path -------------------------------- #
# model: 
#   local_path: </path/to/model>

# ---------------------------- Google Bucket Path ---------------------------- #
# model: 
#   bucket_path: gs://<path_to_model_google_bucket>

# ----------------------------- WANDB model Path ----------------------------- #
# model:
#   project: test-project
#   entity: sail_ugr
#   artifact_name: TD3-Eplus-5zone-hot-continuous-stochastic-v1-episodes-5-id-TD3ExperimentExample_2025-02-02_18-31_9jau51uy
#   artifact_type: output
#   artifact_tag: v0
#   artifact_path: Sinergym_output/evaluation/
#   model_path: Sinergym_output/evaluation/best_model.zip

# ---------------------------------------------------------------------------- #
#                                  EVALUATION                                  #
# ---------------------------------------------------------------------------- #
evaluation:
  eval_freq: 2
  eval_length: 1

# ---------------------------------------------------------------------------- #
#                       ENVIRONMENT OVERWRITE PARAMETERS                       #
# ---------------------------------------------------------------------------- #
# Yaml file with environment configuration (Optional)
env_yaml_config: null
# In order to overwrite some parameters of the environment, you can use the following
env_params:
  seed: null
  reward: sinergym.utils.rewards:LinearReward
# ... other environment parameters



# ---------------------------------------------------------------------------- #
#                              WRAPPERS DEFINITION                             #
# ---------------------------------------------------------------------------- #
# Yaml file with wrappers configuration (Optional)
wrappers_yaml_config: null
# This overwrite wrappers in wrappers_yaml_config if defined
wrappers:
  - sinergym.utils.wrappers:NormalizeAction: {}
  - sinergym.utils.wrappers:NormalizeObservation: {}
  - sinergym.utils.wrappers:LoggerWrapper:
      storage_class: sinergym.utils.logger:LoggerStorage
  - sinergym.utils.wrappers:CSVLogger: {}
  - sinergym.utils.wrappers:WandBLogger:
      entity: alejandro-campoy
      project_name: test-project


# ---------------------------------------------------------------------------- #
#                            GOOGLE CLOUD (OPTIONAL)                           #
# ---------------------------------------------------------------------------- #
cloud: 
  remote_store: null # remote bucket name
  auto_delete: null # Delete remote instance when finish experiment
  # auto_delete:
  #   group_name: group-example
